humanDetect:
    tSize: 200
costMap:
    mapSize: 100
    visSize: 501
    h_self: 80
    h_top: 180
    feld: 500
pR:
    capasity: 15
    featureNum: 4
showImg:
    ObMap: 0
    CostMap: 0
    LiveVideo: 1
    PointCloud: 0
FPS:
    FPS: 1
RosTopic:
    Image: '/zed2/zed_node/left/image_rect_color'
    Video: '/yf_camera/LiveVideo'
    PointCloud: '/zed2/zed_node/point_cloud/cloud_registered'
    ObjectsArray: '/zed2/zed_node/obj_det/objects_yf'
    Goal: '/move_base_simple/goal'
    CostMap: '/yf_camera/obmap'
    RealSpeed: '/real_speed'
    SollSpeed: '/soll_speed'
    ObjectFlag: '/yf_camera/flag'
    ShowMap: '/yf_camera/costmap'
    SollSpeedWEB: '/SollSpeed'
