#==============#
#   DWA Model  #
#==============#
# SMART CAR STATE
Car_State:
    max_speed: 0.8 # [m/s]
    min_speed: -0.8 # [m/s]
    max_yaw_rate: 180.0 # [grad/s]
    max_accel: 4.0  # [m/ss]
    max_delta_yaw_rate: 360.0  # [grad/ss]
    v_resolution: 0.2  # [m/s]
    yaw_rate_resolution: 15. # [grad/s]
    dt: 0.2  # [s] Time tick for motion prediction
    predict_time: 0.8  # [s]  less and more flexible
    to_goal_cost_gain: 0.16
    speed_cost_gain: 0.394
    obstacle_cost_gain: 0.6
    dist_to_goal: 1e10
    dead_count: 0

# FLAG STATE
Flag_State:
    SHOW_ANIMATION: True
    GOAL_ARRIVAED: False
    RESET_STATE: False
    HUMAN_SHAPE: False
    MAP_TO_OBCOORD: True
    MEASURE_TIME: False
    TRANSFORM_MAP: False
